# Development environment configuration
spring:
  application:
    name: containers
  datasource:
    url: jdbc:postgresql://localhost:5432/test_containers_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  security:
    token:
      secret: "mySuperSecretKeyWithAtLeast32Characters!!"
      expiration: 60
    refresh:
      token:
        expiration: 1440

admin:
  email: admin@admin.com
  password: "$2a$12$Ftg9Me9WdLA/d3fPgs4ySu1.V2p/iZ4pHSLfK3Oqk/GvbHjNsW3M."
  first-name: "Admin"