# Test-specific application properties
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    token:
      secret: your-secret-key
      expiration: 3600000
    refresh:
      token:
        expiration: 86400000

admin:
  email: "admin-test@admin.com"
  password: "$2a$12$8j9O14u/JCXQ6vO75X0RaesViv/yczajA40qhAKjkSkIrpQ6FEltK"
  password-decrypted: "secret_admin_test"
  first-name: "Admin Test"

user:
  email: "user-test@user.com"
  password: "$2a$12$ez6gIcPAotEqx4Wd6Uea6.Rgugyo4428nOgVCNj3HzMHwuVIiTw5y"
  password-decrypted: "secret_user_test"
  first-name: "User Test"